### ISSUE TITLE
for TYPO3 7.6 ?

### ISSUE THREAD

**Issue by ingeniumdesign** [jonathanheilmann/ext-jh_pwcomments_captcha#5]
hi Jonathan,
thanks for the nice Ext. but i need this for the TYPO3 7.6
u can update the ext?

thanks!

**Comment by jonathanheilmann** [comment]
Actually, there is no offical version of pw_comments in TER and I didn't tested actual version for TYPO3 CMS 7.2 in 7.6.
Did you test it and does it work? If it works, I'll update my extension soon.

**Comment by ingeniumdesign** [comment]
mh, i use the ext from TER.
its the github version new ?
than i test the github version! :)

**Comment by jorejore** [comment]
The extension pwcomments is available for version 8.7. Will this extension be updated as well? If yes, how soon will it be available?
Thanks

**Comment by jonathanheilmann** [comment]
Looks like EXT:captcha is not supported/updated anymore (will be dropped in this extension), but EXT:sr_freecap is still available, thus I'm going to update this extension within the next days.

**Comment by jonathanheilmann** [comment]
Right now I've release [version 1.0.0 (TER link)](https://extensions.typo3.org/extension/pw_comments/). 
[Changelog](https://github.com/jonathanheilmann/ext-jh_pwcomments_captcha/releases/tag/v1.0.0)
